<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Ehenho\Conversation;
use App\Models\Ehenho\Message;
use App\Models\Ehenho\Profile;
use App\Models\Ehenho\Province;
use App\Models\Ehenho\SocialConnection;
use App\Models\Project;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class EhenhoRichDemoSeeder extends Seeder
{
    public function run(): void
    {
        $project = Project::where('code', 'ehenho')->first();
        $projectId = $project?->id ?? 16;

        // Ensure base provinces exist
        if (Province::count() === 0) {
            $this->call(EhenhoProvinceSeeder::class);
        }

        // Ensure Overseas Countries exist in Province catalog
        $overseasProvinces = [
            ['code' => 'US', 'name' => 'Hoa Kỳ (Mỹ)', 'type' => 'quoc_gia'],
            ['code' => 'AU', 'name' => 'Úc (Australia)', 'type' => 'quoc_gia'],
            ['code' => 'CA', 'name' => 'Canada', 'type' => 'quoc_gia'],
            ['code' => 'DE', 'name' => 'Đức (Germany)', 'type' => 'quoc_gia'],
        ];

        foreach ($overseasProvinces as $op) {
            Province::firstOrCreate(
                ['code' => $op['code']],
                ['name' => $op['name'], 'type' => $op['type']]
            );
        }

        $rawProfiles = [
            // ==========================================
            // 1. VIỆT NAM - NỮ (ĐỘC THÂN, LY DỊ, Ở GÓA)
            // ==========================================
            [
                'name' => 'Thu Thảo',
                'gender' => 'female',
                'age' => 28,
                'height' => '162',
                'weight' => '49',
                'education' => 'Đại học',
                'marital_status' => 'Độc thân',
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Quận 1',
                'headline' => 'Tìm bạn gái kết hôn - Hướng tới gia đình hạnh phúc',
                'target_type' => 'Tìm bạn gái kết hôn',
                'body_type' => 'Cân đối',
                'interests' => 'Làm bánh, đọc sách, nghe nhạc acoustic',
                'personality' => 'Dịu dàng, chu đáo, chung thủy',
                'lifestyle' => 'Hiện đại, thích cuộc sống ấm cúng',
                'precious' => 'Gia đình và sự thấu hiểu',
                'occupation' => 'Giáo viên Tiếng Anh',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Uống xã giao',
                'children' => 'Chưa có',
                'about_me' => 'Sinh ra và làm việc tại TP.HCM. Mong muốn tìm bạn đời chân thành, nghiêm túc xây dựng mái ấm tương lai.',
                'looking_for' => 'Bạn nam chín chắn, có đạo đức và sống có trách nhiệm.',
                'avatar' => 'e-henho/images/459168_pv.png',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Ngọc Ánh',
                'gender' => 'female',
                'age' => 26,
                'height' => '160',
                'weight' => '48',
                'education' => 'Đại học',
                'marital_status' => 'Độc thân',
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Cầu Giấy',
                'headline' => 'Tìm người yêu lâu dài cùng đi qua những ngày tháng bình yên',
                'target_type' => 'Tìm người yêu lâu dài',
                'body_type' => 'Dễ thương',
                'interests' => 'Chụp ảnh, du lịch, nuôi mèo',
                'personality' => 'Năng động, ấm áp, lạc quan',
                'lifestyle' => 'Tích cực, lành mạnh',
                'precious' => 'Tình cảm chân thành',
                'occupation' => 'Chuyên viên Marketing',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Uống xã giao',
                'children' => 'Chưa có',
                'about_me' => 'Cô gái Hà Nội thích sự bình yên, mong tìm được một nửa yêu thương và gắn kết dài lâu.',
                'looking_for' => 'Bạn trai ấm áp, biết lắng nghe và có chí tiến thủ.',
                'avatar' => 'e-henho/images/480871_pv.jpg',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Thanh Thảo',
                'gender' => 'female',
                'age' => 27,
                'height' => '165',
                'weight' => '50',
                'education' => 'Đại học',
                'marital_status' => 'Độc thân',
                'province_name' => 'Thành phố Đà Nẵng',
                'district_name' => 'Hải Châu',
                'headline' => 'Tìm bạn gái tâm sự, sẻ chia vui buồn cuộc sống',
                'target_type' => 'Tìm bạn gái tâm sự',
                'body_type' => 'Mảnh mai',
                'interests' => 'Vẽ tranh, biển, yoga',
                'personality' => 'Nhẹ nhàng, sâu sắc, tinh tế',
                'lifestyle' => 'Yêu thiên nhiên',
                'precious' => 'Sự chân thành',
                'occupation' => 'Thiết kế đồ họa',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Không uống rượu bia',
                'children' => 'Chưa có',
                'about_me' => 'Sống tại Đà Nẵng, mong tìm người có thể lắng nghe và chia sẻ chân thành mọi điều trong cuộc sống.',
                'looking_for' => 'Người bạn tâm sự chân tình, đáng tin cậy.',
                'avatar' => 'e-henho/images/474569_pv.jpg',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Khánh Vy',
                'gender' => 'female',
                'age' => 25,
                'height' => '163',
                'weight' => '48',
                'education' => 'Đại học',
                'marital_status' => 'Độc thân',
                'province_name' => 'Thành phố Cần Thơ',
                'district_name' => 'Ninh Kiều',
                'headline' => 'Tìm bạn gái làm quen, mở rộng kết nối bạn bè',
                'target_type' => 'Tìm bạn gái làm quen',
                'body_type' => 'Cân đối',
                'interests' => 'Ẩm thực miền Tây, hát acoustic',
                'personality' => 'Cởi mở, hòa đồng, vui vẻ',
                'lifestyle' => 'Tự nhiên, mộc mạc',
                'precious' => 'Tình bạn bè',
                'occupation' => 'Nhân viên ngân hàng',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Không uống rượu bia',
                'children' => 'Chưa có',
                'about_me' => 'Gái miền Tây tính tình thẳng thắn, vui vẻ. Rất mong kết bạn làm quen với mọi người bốn phương.',
                'looking_for' => 'Những người bạn chân thật, văn minh.',
                'avatar' => 'e-henho/images/421749_pv.jpg',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Hương Giang',
                'gender' => 'female',
                'age' => 34,
                'height' => '161',
                'weight' => '52',
                'education' => 'Đại học',
                'marital_status' => 'Ly dị',
                'province_name' => 'Thành phố Hải Phòng',
                'district_name' => 'Lê Chân',
                'headline' => 'Tìm bạn gái ly dị - Tìm một nửa cảm thông và thấu hiểu',
                'target_type' => 'Tìm một nửa',
                'body_type' => 'Cân đối',
                'interests' => 'Nấu ăn, cắm hoa, du lịch',
                'personality' => 'Chín chắn, chu đáo, giàu tình cảm',
                'lifestyle' => 'Độc lập, tích cực',
                'precious' => 'Bình yên bên con và gia đình',
                'occupation' => 'Kế toán trưởng',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Uống xã giao',
                'children' => 'Đã có 1 con',
                'about_me' => 'Đã ly hôn, hiện sống và làm việc tại Hải Phòng. Mong tìm một người đàn ông bao dung, cùng nhau bước tiếp.',
                'looking_for' => 'Người đàn ông trưởng thành, có bản lĩnh và yêu thương con trẻ.',
                'avatar' => 'e-henho/images/87396_pv.jpg',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Kim Oanh',
                'gender' => 'female',
                'age' => 42,
                'height' => '158',
                'weight' => '51',
                'education' => 'Cao đẳng',
                'marital_status' => 'Ở góa',
                'province_name' => 'Thừa Thiên Huế',
                'district_name' => 'TP. Huế',
                'headline' => 'Tìm bạn gái ở góa - Tìm bạn trăm năm nương tựa tuổi xế chiều',
                'target_type' => 'Tìm bạn trăm năm',
                'body_type' => 'Mảnh mai',
                'interests' => 'Thiền định, chăm sóc cây cảnh, trà đạo',
                'personality' => 'Hiền hậu, nhã nhặn, kín đáo',
                'lifestyle' => 'Thanh thản, truyền thống',
                'precious' => 'Sự thủy chung',
                'occupation' => 'Kinh doanh gia đình',
                'religion' => 'Phật giáo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Không uống rượu bia',
                'children' => 'Con đã lớn',
                'about_me' => 'Chồng mất nhiều năm, hiện các con đều đã tự lập. Mong tìm bạn trăm năm cùng trò chuyện, sẻ chia.',
                'looking_for' => 'Bạn nam đứng đắn, tôn trọng văn hóa gia đình.',
                'avatar' => 'e-henho/images/478981_pv.jpg',
                'is_featured' => false,
                'is_online' => false,
            ],
            [
                'name' => 'Đàn Bà Cũ',
                'gender' => 'female',
                'age' => 41,
                'height' => '159',
                'weight' => '53',
                'education' => 'Đại học',
                'marital_status' => 'Ly dị',
                'province_name' => 'Tỉnh Lâm Đồng',
                'district_name' => 'TP. Đà Lạt',
                'headline' => 'Tìm bạn gái ly dị - Cần một người hiểu và bao dung',
                'target_type' => 'Tìm bạn đời',
                'body_type' => 'Mảnh mai',
                'interests' => 'Trồng hoa, làm vườn, acoustic',
                'personality' => 'Trầm tính, sống nội tâm, sâu sắc',
                'lifestyle' => 'Yên tĩnh, mộc mạc',
                'precious' => 'Tình cảm gia đình',
                'occupation' => 'Kinh doanh homestay',
                'religion' => 'Phật giáo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Không uống rượu bia',
                'children' => 'Đã có 1 con',
                'about_me' => 'Đã qua một lần dang dở nên rất trân trọng hạnh phúc giản đơn ở phố núi Đà Lạt. Mong tìm được tri kỷ.',
                'looking_for' => 'Người đàn ông trưởng thành, biết đồng cảm và trân trọng tình nghĩa.',
                'avatar' => 'e-henho/images/487168_pv.jpeg',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Mai Lan',
                'gender' => 'female',
                'age' => 29,
                'height' => '164',
                'weight' => '50',
                'education' => 'Đại học',
                'marital_status' => 'Độc thân',
                'province_name' => 'Tỉnh Khánh Hòa',
                'district_name' => 'Nha Trang',
                'headline' => 'Tìm vợ - Tìm người bạn đời nghiêm túc tiến tới hôn nhân',
                'target_type' => 'Tìm vợ',
                'body_type' => 'Cân đối',
                'interests' => 'Bơi lội, du lịch biển, làm bánh',
                'personality' => 'Thân thiện, nữ tính, tự tin',
                'lifestyle' => 'Lành mạnh, yêu đời',
                'precious' => 'Hạnh phúc lứa đôi',
                'occupation' => 'Quản trị khách sạn',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Uống xã giao',
                'children' => 'Chưa có',
                'about_me' => 'Làm việc tại Nha Trang, mong muốn tìm bạn trai nghiêm túc để kết hôn và xây dựng tổ ấm nhỏ.',
                'looking_for' => 'Bạn trai có công việc ổn định, tính tình vui vẻ, thật thà.',
                'avatar' => 'e-henho/images/251850_pv.jpg',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Mỹ Duyên',
                'gender' => 'female',
                'age' => 31,
                'height' => '162',
                'weight' => '51',
                'education' => 'Đại học',
                'marital_status' => 'Độc thân',
                'province_name' => 'Tỉnh Đồng Nai',
                'district_name' => 'Biên Hòa',
                'headline' => 'Tìm bạn chat, giao lưu kết nối những tâm hồn đồng điệu',
                'target_type' => 'Tìm bạn chat',
                'body_type' => 'Cân đối',
                'interests' => 'Nghe nhạc, cà phê, xem phim',
                'personality' => 'Dễ mến, hay cười, thấu cảm',
                'lifestyle' => 'Giản dị',
                'precious' => 'Sự chân thành',
                'occupation' => 'Dược sĩ',
                'religion' => 'Công giáo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Không uống rượu bia',
                'children' => 'Chưa có',
                'about_me' => 'Ở Biên Hòa, sau giờ làm việc thích trò chuyện tâm sự cùng bạn bè tử tế.',
                'looking_for' => 'Bạn bè trò chuyện lịch sự, tôn trọng lẫn nhau.',
                'avatar' => 'e-henho/images/114027_pl.png',
                'is_featured' => false,
                'is_online' => true,
            ],
            [
                'name' => 'Hà My',
                'gender' => 'female',
                'age' => 24,
                'height' => '166',
                'weight' => '49',
                'education' => 'Đại học',
                'marital_status' => 'Độc thân',
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Quận 7',
                'headline' => 'Tìm người yêu ngắn hạn, giao lưu hẹn hò văn minh',
                'target_type' => 'Tìm người yêu ngắn hạn',
                'body_type' => 'Gợi cảm',
                'interests' => 'Thời trang, khiêu vũ, ẩm thực',
                'personality' => 'Năng động, phóng khoáng, hiện đại',
                'lifestyle' => 'Hiện đại, sành điệu',
                'precious' => 'Tự do và sự tôn trọng',
                'occupation' => 'Kinh doanh online',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Uống xã giao',
                'children' => 'Chưa có',
                'about_me' => 'Thích gặp gỡ những người bạn thú vị, cùng trải nghiệm những buổi hẹn hò nhẹ nhàng, không ràng buộc.',
                'looking_for' => 'Bạn nam lịch sự, ngoại hình sáng, tôn trọng đối phương.',
                'avatar' => 'e-henho/images/154699_pl.jpeg',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Thùy Trang',
                'gender' => 'female',
                'age' => 45,
                'height' => '157',
                'weight' => '54',
                'education' => 'Cao học',
                'marital_status' => 'Ở góa',
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Tây Hồ',
                'headline' => 'Tìm bạn ở góa - Tìm bạn đời gắn bó những năm tháng sau này',
                'target_type' => 'Tìm bạn đời',
                'body_type' => 'Cân đối',
                'interests' => 'Đi bộ, làm vườn, nhạc cổ điển',
                'personality' => 'Điềm tĩnh, ấm áp, sâu sắc',
                'lifestyle' => 'Thanh lịch',
                'precious' => 'Tình nghĩa gia đình',
                'occupation' => 'Giảng viên đại học',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Không uống rượu bia',
                'children' => 'Đã có 2 con',
                'about_me' => 'Sống tại Hà Nội, mong tìm được người bạn tri kỷ để bầu bạn, chia sẻ niềm vui trong cuộc sống.',
                'looking_for' => 'Bạn nam trí thức, sống tình nghĩa, biết sẻ chia.',
                'avatar' => 'e-henho/images/168090_pl.jpg',
                'is_featured' => false,
                'is_online' => false,
            ],

            // ==========================================
            // 2. VIỆT NAM - NAM (ĐỘC THÂN, LY DỊ, Ở GÓA)
            // ==========================================
            [
                'name' => 'Võ Thanh Hải',
                'gender' => 'male',
                'age' => 42,
                'height' => '176',
                'weight' => '75',
                'education' => 'Cao học',
                'marital_status' => 'Độc thân',
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_name' => 'Quận 3',
                'headline' => 'Tìm bạn trai kết hôn - Doanh nhân tìm bạn đời nghiêm túc',
                'target_type' => 'Tìm bạn trai kết hôn',
                'body_type' => 'Cao lớn',
                'interests' => 'Kiến trúc, du lịch, nấu ăn',
                'personality' => 'Mạnh mẽ, chân thành, có trách nhiệm',
                'lifestyle' => 'Lành mạnh, chuẩn mực',
                'precious' => 'Tổ ấm gia đình',
                'occupation' => 'Chủ doanh nghiệp',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Uống xã giao',
                'children' => 'Chưa có',
                'about_me' => 'Kinh tế vững vàng, công việc ổn định. Rất mong tìm được bạn nữ cùng chung chí hướng xây dựng gia đình.',
                'looking_for' => 'Bạn nữ hiền dịu, biết quan tâm và chia sẻ.',
                'avatar' => 'e-henho/images/486975_pv.jpg',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Quang Minh',
                'gender' => 'male',
                'age' => 33,
                'height' => '174',
                'weight' => '69',
                'education' => 'Đại học',
                'marital_status' => 'Độc thân',
                'province_name' => 'Thành phố Hà Nội',
                'district_name' => 'Hoàn Kiếm',
                'headline' => 'Tìm bạn trai độc thân - Kỹ sư công nghệ hướng tới tương lai',
                'target_type' => 'Tìm bạn trai độc thân',
                'body_type' => 'Cân đối',
                'interests' => 'Bóng đá, cà phê, công nghệ',
                'personality' => 'Chững chạc, thật thà, hài hước',
                'lifestyle' => 'Kỷ luật, năng động',
                'precious' => 'Sự tin tưởng',
                'occupation' => 'Kỹ sư phần mềm',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Uống xã giao',
                'children' => 'Chưa có',
                'about_me' => 'Sống và làm việc tại Hà Nội. Độc lập tài chính, sẵn sàng cho việc lập gia đình.',
                'looking_for' => 'Bạn nữ dễ thương, chân thật và sống có đạo đức.',
                'avatar' => 'e-henho/images/490459_pl.png',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Trần Hoàng',
                'gender' => 'male',
                'age' => 37,
                'height' => '172',
                'weight' => '71',
                'education' => 'Đại học',
                'marital_status' => 'Ly dị',
                'province_name' => 'Thành phố Đà Nẵng',
                'district_name' => 'Sơn Trà',
                'headline' => 'Tìm bạn trai ly dị - Cần một người bạn đồng hành tin cậy',
                'target_type' => 'Tìm bạn trai ly dị',
                'body_type' => 'Cân đối',
                'interests' => 'Chạy bộ, câu cá, du lịch',
                'personality' => 'Thẳng thắn, biết lắng nghe',
                'lifestyle' => 'Đơn giản, tự lập',
                'precious' => 'Sự chân thành',
                'occupation' => 'Quản lý dự án',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Uống xã giao',
                'children' => 'Đã có 1 con',
                'about_me' => 'Đã qua đổ vỡ hôn nhân nên rất trân quý tình cảm thật lòng. Sống và làm việc tại Đà Nẵng.',
                'looking_for' => 'Bạn nữ biết cảm thông, cùng xây dựng cuộc sống bình an.',
                'avatar' => 'e-henho/images/408951_pl.jpg',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Thành Nam',
                'gender' => 'male',
                'age' => 48,
                'height' => '173',
                'weight' => '74',
                'education' => 'Đại học',
                'marital_status' => 'Ở góa',
                'province_name' => 'Thành phố Hải Phòng',
                'district_name' => 'Ngô Quyền',
                'headline' => 'Tìm bạn trai ở góa - Tìm người bạn tri kỷ sẻ chia năm tháng',
                'target_type' => 'Tìm bạn trai ở góa',
                'body_type' => 'Cao lớn',
                'interests' => 'Đọc sách, làm vườn, thể thao',
                'personality' => 'Chững chạc, chu đáo, điềm đạm',
                'lifestyle' => 'Mực thước, gia giáo',
                'precious' => 'Tổ ấm gia đình',
                'occupation' => 'Kinh doanh xuất nhập khẩu',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Không uống rượu bia',
                'children' => 'Con đã lớn',
                'about_me' => 'Vợ mất đã lâu, các con đều đã ổn định. Tìm bạn nữ đứng đắn để bầu bạn và chăm sóc lẫn nhau.',
                'looking_for' => 'Người bạn gái nhân hậu, biết chia sẻ niềm vui giản dị.',
                'avatar' => 'e-henho/images/480456_pl.jpg',
                'is_featured' => false,
                'is_online' => false,
            ],
            [
                'name' => 'Đình Trọng',
                'gender' => 'male',
                'age' => 31,
                'height' => '177',
                'weight' => '73',
                'education' => 'Đại học',
                'marital_status' => 'Độc thân',
                'province_name' => 'Thành phố Cần Thơ',
                'district_name' => 'Cái Răng',
                'headline' => 'Tìm chồng - Tìm người yêu lâu dài hướng tới hôn nhân',
                'target_type' => 'Tìm chồng',
                'body_type' => 'Cân đối',
                'interests' => 'Cầu lông, du lịch sinh thái',
                'personality' => 'Hiền lành, chịu khó, có trách nhiệm',
                'lifestyle' => 'Đơn giản, hướng về gia đình',
                'precious' => 'Tình nghĩa',
                'occupation' => 'Kỹ sư nông nghiệp',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Uống xã giao',
                'children' => 'Chưa có',
                'about_me' => 'Thanh niên miền Tây chân thật, công việc ổn định tại Cần Thơ. Muốn tìm bạn đời trăm năm.',
                'looking_for' => 'Bạn gái thật lòng, biết yêu thương cha mẹ.',
                'avatar' => 'e-henho/images/463736_pl.jpg',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Bảo Long',
                'gender' => 'male',
                'age' => 35,
                'height' => '175',
                'weight' => '70',
                'education' => 'Đại học',
                'marital_status' => 'Độc thân',
                'province_name' => 'Thừa Thiên Huế',
                'district_name' => 'TP. Huế',
                'headline' => 'Tìm bạn trai tâm sự, chia sẻ chuyện đời chuyện người',
                'target_type' => 'Tìm bạn trai tâm sự',
                'body_type' => 'Cân đối',
                'interests' => 'Nhiếp ảnh, thư pháp, ca Huế',
                'personality' => 'Trầm ấm, sâu lắng, tinh tế',
                'lifestyle' => 'Nhẹ nhàng, thư thả',
                'precious' => 'Sự đồng điệu tâm hồn',
                'occupation' => 'Nhà báo tự do',
                'religion' => 'Phật giáo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Uống trà',
                'children' => 'Chưa có',
                'about_me' => 'Chàng trai xứ Huế yêu nét cổ kính, mong tìm người có thể trò chuyện sâu sắc về văn hóa và cuộc sống.',
                'looking_for' => 'Bạn gái có tâm hồn tinh tế, đồng cảm.',
                'avatar' => 'e-henho/images/10761_pl.jpg',
                'is_featured' => false,
                'is_online' => true,
            ],
            [
                'name' => 'Minh Hùng',
                'gender' => 'male',
                'age' => 29,
                'height' => '178',
                'weight' => '72',
                'education' => 'Đại học',
                'marital_status' => 'Độc thân',
                'province_name' => 'Tỉnh Khánh Hòa',
                'district_name' => 'Cam Ranh',
                'headline' => 'Tìm bạn trai làm quen, giao lưu kết nối chân tình',
                'target_type' => 'Tìm bạn trai làm quen',
                'body_type' => 'Cao lớn',
                'interests' => 'Tập gym, bóng rổ, lặn biển',
                'personality' => 'Vui tính, ga lăng, cởi mở',
                'lifestyle' => 'Thích vận động',
                'precious' => 'Sức khỏe và tình bạn',
                'occupation' => 'Huấn luyện viên thể thao',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Uống xã giao',
                'children' => 'Chưa có',
                'about_me' => 'Yêu biển Khánh Hòa, tính tình phóng khoáng. Rất vui làm quen với các bạn trên eHenho.',
                'looking_for' => 'Bạn gái dễ thương, năng động.',
                'avatar' => 'e-henho/images/112096_pl.jpg',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Quốc Việt',
                'gender' => 'male',
                'age' => 44,
                'height' => '171',
                'weight' => '68',
                'education' => 'Đại học',
                'marital_status' => 'Ly dị',
                'province_name' => 'Tỉnh Lâm Đồng',
                'district_name' => 'Bảo Lộc',
                'headline' => 'Tìm một nửa yêu thương - Tìm bạn ly dị cùng chí hướng',
                'target_type' => 'Tìm một nửa',
                'body_type' => 'Cân đối',
                'interests' => 'Làm nông nghiệp sạch, trà olong',
                'personality' => 'Chân chất, hiền lành, bền bỉ',
                'lifestyle' => 'Yên bình nơi thôn dã',
                'precious' => 'Sự thủy chung',
                'occupation' => 'Chủ trang trại trà',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Không uống rượu bia',
                'children' => 'Đã có 1 con',
                'about_me' => 'Sau biến cố hôn nhân, hiện sinh sống và phát triển nông trại tại Bảo Lộc. Mong tìm bạn đời gắn kết.',
                'looking_for' => 'Người bạn đời chân thành, giản dị.',
                'avatar' => 'e-henho/images/126785_pl.jpg',
                'is_featured' => false,
                'is_online' => false,
            ],
            [
                'name' => 'Đức Thịnh',
                'gender' => 'male',
                'age' => 36,
                'height' => '174',
                'weight' => '71',
                'education' => 'Đại học',
                'marital_status' => 'Độc thân',
                'province_name' => 'Tỉnh Đồng Nai',
                'district_name' => 'Long Thành',
                'headline' => 'Tìm bạn trăm năm - Tìm người yêu lâu dài xây đắp tương lai',
                'target_type' => 'Tìm bạn trăm năm',
                'body_type' => 'Cân đối',
                'interests' => 'Đầu tư, du lịch phượt, nấu ăn',
                'personality' => 'Chín chắn, chu đáo, có chí tiến thủ',
                'lifestyle' => 'Hiện đại, tích cực',
                'precious' => 'Hạnh phúc gia đình',
                'occupation' => 'Kỹ sư cơ khí',
                'religion' => 'Công giáo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Uống xã giao',
                'children' => 'Chưa có',
                'about_me' => 'Làm việc tại Đồng Nai, sống độc lập và tự chủ. Mong tìm bạn nữ hợp duyên tiến tới hôn nhân.',
                'looking_for' => 'Bạn gái đoan trang, tôn trọng gia đình hai bên.',
                'avatar' => 'e-henho/images/142241_pl.jpg',
                'is_featured' => true,
                'is_online' => true,
            ],

            // ==========================================
            // 3. NƯỚC NGOÀI & VIỆT KIỀU (MỸ, ÚC, CANADA, ĐỨC)
            // ==========================================
            [
                'name' => 'Peter Nguyen',
                'gender' => 'male',
                'age' => 38,
                'height' => '178',
                'weight' => '76',
                'education' => 'Thạc sĩ',
                'marital_status' => 'Độc thân',
                'province_name' => 'Hoa Kỳ (Mỹ)',
                'district_name' => 'California - San Jose',
                'headline' => 'Tìm bạn bốn phương Việt kiều Mỹ - Tìm bạn gái kết hôn',
                'target_type' => 'Tìm bạn gái kết hôn',
                'body_type' => 'Cao lớn',
                'interests' => 'Công nghệ, du lịch thế giới, ẩm thực Việt',
                'personality' => 'Hiện đại, lịch thiệp, giữ gìn truyền thống Việt',
                'lifestyle' => 'Tây hóa nhưng yêu quê hương',
                'precious' => 'Gia đình Việt',
                'occupation' => 'Kỹ sư cao cấp Thung lũng Silicon',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Uống vang xã giao',
                'children' => 'Chưa có',
                'about_me' => 'Định cư tại California, Mỹ hơn 15 năm. Công việc và nhà cửa ổn định. Muốn tìm bạn gái Việt Nam tiến tới hôn nhân và bảo lãnh sang Mỹ.',
                'looking_for' => 'Bạn gái truyền thống, hiền hậu, nói tiếng Anh cơ bản.',
                'avatar' => 'e-henho/images/154782_pl.jpg',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Jennifer Le',
                'gender' => 'female',
                'age' => 32,
                'height' => '165',
                'weight' => '50',
                'education' => 'Đại học',
                'marital_status' => 'Độc thân',
                'province_name' => 'Hoa Kỳ (Mỹ)',
                'district_name' => 'Texas - Houston',
                'headline' => 'Tìm bạn bốn phương ở Mỹ - Tìm bạn đời chân thành',
                'target_type' => 'Tìm bạn đời',
                'body_type' => 'Duyên dáng',
                'interests' => 'Nấu món Việt, yoga, làm từ thiện',
                'personality' => 'Tự tin, ấm áp, chu đáo',
                'lifestyle' => 'Hiện đại, năng động',
                'precious' => 'Tình yêu chân thực',
                'occupation' => 'Nha sĩ',
                'religion' => 'Công giáo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Uống xã giao',
                'children' => 'Chưa có',
                'about_me' => 'Việt kiều Mỹ tại Houston, Texas. Mong tìm một người đàn ông Việt đàng hoàng, có chí hướng để cùng sẻ chia cuộc sống.',
                'looking_for' => 'Bạn trai có đạo đức, yêu thương gia đình.',
                'avatar' => 'e-henho/images/207818_pl.jpeg',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'David Vu',
                'gender' => 'male',
                'age' => 45,
                'height' => '174',
                'weight' => '72',
                'education' => 'Đại học',
                'marital_status' => 'Ly dị',
                'province_name' => 'Hoa Kỳ (Mỹ)',
                'district_name' => 'California - Westminster',
                'headline' => 'Tìm bạn bốn phương Việt kiều - Tìm một nửa yêu thương',
                'target_type' => 'Tìm một nửa',
                'body_type' => 'Cân đối',
                'interests' => 'Golf, câu cá, âm nhạc quê hương',
                'personality' => 'Chín chắn, bao dung, thật thà',
                'lifestyle' => 'Đàng hoàng, ổn định',
                'precious' => 'Tổ ấm an vui',
                'occupation' => 'Chủ nhà hàng Việt tại Mỹ',
                'religion' => 'Phật giáo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Không uống rượu bia',
                'children' => 'Đã có 1 con',
                'about_me' => 'Việt kiều tại Quận Cam, California. Đã ly hôn nhiều năm, kinh tế rất vững vàng. Muốn tìm bạn gái đồng cảm, sẵn sàng qua Mỹ xây dựng hạnh phúc mới.',
                'looking_for' => 'Bạn gái biết chăm sóc gia đình, chân thật.',
                'avatar' => 'e-henho/images/175368_pl.jpg',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Alex Tran',
                'gender' => 'male',
                'age' => 36,
                'height' => '177',
                'weight' => '74',
                'education' => 'Thạc sĩ',
                'marital_status' => 'Độc thân',
                'province_name' => 'Úc (Australia)',
                'district_name' => 'Sydney - Bankstown',
                'headline' => 'Tìm bạn bốn phương ở Úc - Tìm người yêu lâu dài hướng tới tương lai',
                'target_type' => 'Tìm người yêu lâu dài',
                'body_type' => 'Cao lớn',
                'interests' => 'Lướt sóng, bóng đá, du lịch',
                'personality' => 'Cởi mở, vui vẻ, bản lĩnh',
                'lifestyle' => 'Khỏe khoắn, tích cực',
                'precious' => 'Sự thủy chung',
                'occupation' => 'Chuyên gia Tài chính',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Uống bia xã giao',
                'children' => 'Chưa có',
                'about_me' => 'Sống và làm việc tại Sydney, Úc. Đã có quốc tịch Úc. Mong muốn tìm bạn gái Việt Nam để gắn bó trăm năm.',
                'looking_for' => 'Bạn gái dịu dàng, nết na, nghiêm túc trong tình cảm.',
                'avatar' => 'e-henho/images/194965_pl.jpg',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Grace Pham',
                'gender' => 'female',
                'age' => 30,
                'height' => '163',
                'weight' => '49',
                'education' => 'Đại học',
                'marital_status' => 'Độc thân',
                'province_name' => 'Úc (Australia)',
                'district_name' => 'Melbourne - Springvale',
                'headline' => 'Tìm bạn bốn phương nước ngoài - Tìm bạn đời đồng điệu',
                'target_type' => 'Tìm bạn đời',
                'body_type' => 'Mảnh mai',
                'interests' => 'Làm bánh, đọc sách, du lịch',
                'personality' => 'Hiền lành, tình cảm, chu đáo',
                'lifestyle' => 'Hiện đại, ấm áp',
                'precious' => 'Sự thấu hiểu',
                'occupation' => 'Y tá tại Bệnh viện Melbourne',
                'religion' => 'Công giáo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Không uống rượu bia',
                'children' => 'Chưa có',
                'about_me' => 'Việt kiều Úc, sinh sống tại Melbourne. Muốn tìm bạn trai người Việt tử tế, có thể ở Úc hoặc ở Việt Nam.',
                'looking_for' => 'Bạn nam chín chắn, có trách nhiệm.',
                'avatar' => 'e-henho/images/220079_pl.jpeg',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Kevin Dang',
                'gender' => 'male',
                'age' => 40,
                'height' => '175',
                'weight' => '73',
                'education' => 'Đại học',
                'marital_status' => 'Độc thân',
                'province_name' => 'Canada',
                'district_name' => 'Toronto - Ontario',
                'headline' => 'Tìm bạn bốn phương ở Canada - Tìm vợ hiền dâu thảo',
                'target_type' => 'Tìm vợ',
                'body_type' => 'Cân đối',
                'interests' => 'Trượt tuyết, cắm trại, nấu món ăn Việt',
                'personality' => 'Ấm áp, vững vàng, ga lăng',
                'lifestyle' => 'Gọn gàng, lành mạnh',
                'precious' => 'Mái ấm sum vầy',
                'occupation' => 'Chuyên viên IT ngân hàng Canada',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Uống xã giao',
                'children' => 'Chưa có',
                'about_me' => 'Định cư Canada đã 10 năm, nhà cửa xe cộ đầy đủ. Mùa đông ở Toronto lạnh nên mong tìm được một nửa sưởi ấm trái tim.',
                'looking_for' => 'Bạn gái chân thật, biết chăm lo gia đình.',
                'avatar' => 'e-henho/images/230802_pl.jpg',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Sophie Do',
                'gender' => 'female',
                'age' => 33,
                'height' => '162',
                'weight' => '50',
                'education' => 'Thạc sĩ',
                'marital_status' => 'Độc thân',
                'province_name' => 'Canada',
                'district_name' => 'Vancouver - British Columbia',
                'headline' => 'Tìm bạn trai kết hôn - Gái Việt tại Canada tìm bạn đời',
                'target_type' => 'Tìm bạn trai kết hôn',
                'body_type' => 'Cân đối',
                'interests' => 'Hiking, chụp ảnh thiên nhiên, làm bánh',
                'personality' => 'Thông minh, độc lập, vui tươi',
                'lifestyle' => 'Yêu thiên nhiên, tích cực',
                'precious' => 'Tình yêu chân chính',
                'occupation' => 'Kiến trúc sư cảnh quan',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Không uống rượu bia',
                'children' => 'Chưa có',
                'about_me' => 'Sống tại thành phố biển Vancouver xinh đẹp. Rất nhớ quê hương và muốn tìm một nửa là người Việt Nam.',
                'looking_for' => 'Bạn trai chân thành, học thức, tôn trọng gia đình.',
                'avatar' => 'e-henho/images/245616_pl.jpeg',
                'is_featured' => false,
                'is_online' => true,
            ],
            [
                'name' => 'Marcus Nguyen',
                'gender' => 'male',
                'age' => 43,
                'height' => '176',
                'weight' => '75',
                'education' => 'Kỹ sư',
                'marital_status' => 'Ly dị',
                'province_name' => 'Đức (Germany)',
                'district_name' => 'Berlin - Mitte',
                'headline' => 'Tìm bạn bốn phương ở Đức - Tìm bạn trăm năm nương tựa',
                'target_type' => 'Tìm bạn trăm năm',
                'body_type' => 'Cao lớn',
                'interests' => 'Kỹ thuật ô tô, du lịch châu Âu, nấu ăn',
                'personality' => 'Chính trực, cần cù, sống tình nghĩa',
                'lifestyle' => 'Quy củ, ngăn nắp',
                'precious' => 'Tình cảm gia đình',
                'occupation' => 'Kỹ sư cơ khí chính xác tại Berlin',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Uống bia Đức xã giao',
                'children' => 'Đã có 1 con',
                'about_me' => 'Định cư tại Đức hơn 20 năm. Đã qua một lần đò, hiện cuộc sống ổn định. Rất muốn đón một người bạn gái Việt sang Đức cùng nhau xây đắp hạnh phúc.',
                'looking_for' => 'Bạn nữ chân thật, chịu khó và biết chăm lo tổ ấm.',
                'avatar' => 'e-henho/images/261995_pl.jpg',
                'is_featured' => true,
                'is_online' => true,
            ],
            [
                'name' => 'Anna Nguyen',
                'gender' => 'female',
                'age' => 35,
                'height' => '160',
                'weight' => '49',
                'education' => 'Đại học',
                'marital_status' => 'Độc thân',
                'province_name' => 'Đức (Germany)',
                'district_name' => 'Frankfurt',
                'headline' => 'Tìm bạn gái tâm sự - Tìm bạn bốn phương Việt kiều Đức',
                'target_type' => 'Tìm bạn gái tâm sự',
                'body_type' => 'Cân đối',
                'interests' => 'Âm nhạc cổ điển, du lịch, nấu nướng',
                'personality' => 'Dịu dàng, hiền hậu, chu đáo',
                'lifestyle' => 'Yên bình',
                'precious' => 'Sự thấu hiểu',
                'occupation' => 'Dược sĩ tại Frankfurt',
                'religion' => 'Không đạo',
                'smoking' => 'Không hút thuốc',
                'drinking' => 'Không uống rượu bia',
                'children' => 'Chưa có',
                'about_me' => 'Ở Đức đã lâu, xa quê hương nên luôn mong tìm được người bạn đồng điệu tâm sự về cuộc sống và quê nhà.',
                'looking_for' => 'Người bạn biết lắng nghe, chân tình.',
                'avatar' => 'e-henho/images/253880_pl.png',
                'is_featured' => true,
                'is_online' => true,
            ],
        ];

        $createdProfiles = [];

        $tenantId = $project?->tenant_id ?? 7;

        foreach ($rawProfiles as $idx => $pData) {
            $userEmail = 'user_'.Str::slug($pData['name'], '_').'_'.($idx + 1).'@ehenho.local';

            $user = User::withoutGlobalScopes()->where('email', $userEmail)->first();
            if (! $user) {
                $candidateUsername = 'user_ehenho_'.($idx + 101);
                if (User::withoutGlobalScopes()->where('username', $candidateUsername)->exists()) {
                    $candidateUsername = 'user_ehenho_'.($idx + 101).'_'.substr(md5($userEmail), 0, 4);
                }

                $user = User::create([
                    'tenant_id' => $tenantId,
                    'project_ids' => [$projectId],
                    'name' => $pData['name'],
                    'email' => $userEmail,
                    'username' => $candidateUsername,
                    'password' => Hash::make('123456'),
                    'role' => 'user',
                    'status' => 1,
                    'gold' => 100,
                ]);
            } else {
                if (empty($user->tenant_id)) {
                    $user->tenant_id = $tenantId;
                    $user->project_ids = [$projectId];
                    $user->save();
                }
            }

            // Match province cleanly
            $cleanProv = str_replace(['Tỉnh ', 'Thành phố '], '', $pData['province_name']);
            $province = Province::where('name', 'like', '%'.$cleanProv.'%')
                ->orWhere('name', 'like', '%'.$pData['province_name'].'%')
                ->first();

            $profile = Profile::updateOrCreate(
                ['user_id' => $user->id],
                [
                    'project_id' => $projectId,
                    'display_name' => $pData['name'],
                    'slug' => Str::slug($pData['name']).'-'.$user->id,
                    'headline' => $pData['headline'],
                    'target_type' => $pData['target_type'],
                    'gender' => $pData['gender'],
                    'birthday' => now()->subYears($pData['age'])->subMonths($idx * 2),
                    'age' => $pData['age'],
                    'province_id' => $province?->id,
                    'province_name' => $province?->name ?? $pData['province_name'],
                    'district_name' => $pData['district_name'],
                    'marital_status' => $pData['marital_status'],
                    'occupation' => $pData['occupation'],
                    'height' => $pData['height'],
                    'weight' => $pData['weight'],
                    'education' => $pData['education'],
                    'body_type' => $pData['body_type'],
                    'interests' => $pData['interests'],
                    'personality' => $pData['personality'],
                    'lifestyle' => $pData['lifestyle'],
                    'precious' => $pData['precious'],
                    'religion' => $pData['religion'],
                    'smoking' => $pData['smoking'],
                    'drinking' => $pData['drinking'],
                    'children' => $pData['children'],
                    'about_me' => $pData['about_me'],
                    'looking_for' => $pData['target_type'].' - '.$pData['looking_for'],
                    'avatar_url' => $pData['avatar'],
                    'is_featured' => $pData['is_featured'],
                    'is_online' => $pData['is_online'],
                    'last_active_at' => now()->subHours($idx * 2),
                    'status' => 'active',
                    'privacy_option' => 'Chỉ nhận tin nhắn từ hồ sơ có hình đại diện.',
                ]
            );

            $createdProfiles[] = $profile;
        }

        // Create sample conversations and messages between users
        if (count($createdProfiles) >= 2) {
            $userA = $createdProfiles[0]->user_id; // Thu Thảo
            $userB = $createdProfiles[11]->user_id; // Võ Thanh Hải

            $conv = Conversation::firstOrCreate([
                'user_one_id' => min($userA, $userB),
                'user_two_id' => max($userA, $userB),
            ], [
                'project_id' => $projectId,
                'last_message_at' => now(),
            ]);

            Message::create([
                'project_id' => $projectId,
                'conversation_id' => $conv->id,
                'sender_id' => $userB,
                'recipient_id' => $userA,
                'subject' => 'Chào bạn Thu Thảo, rất vui được làm quen!',
                'body' => 'Chào Thảo, mình xem hồ sơ thấy bạn rất dễ thương và chân thành. Nếu không phiền thì cho mình kết bạn trò chuyện cùng bạn nhé!',
                'is_read' => true,
                'read_at' => now()->subHours(2),
            ]);

            Message::create([
                'project_id' => $projectId,
                'conversation_id' => $conv->id,
                'sender_id' => $userA,
                'recipient_id' => $userB,
                'subject' => 'Re: Chào bạn Thu Thảo!',
                'body' => 'Chào anh Hải, cảm ơn anh đã nhắn tin cho em. Em cũng rất vui được làm quen với anh!',
                'is_read' => false,
            ]);

            // Sample likes & bookmarks
            SocialConnection::firstOrCreate([
                'user_id' => $userA,
                'target_profile_id' => $createdProfiles[11]->id,
                'relation_type' => 'like',
            ], ['project_id' => $projectId]);

            SocialConnection::firstOrCreate([
                'user_id' => $userA,
                'target_profile_id' => $createdProfiles[11]->id,
                'relation_type' => 'bookmark',
            ], ['project_id' => $projectId]);

            SocialConnection::firstOrCreate([
                'user_id' => $userB,
                'target_profile_id' => $createdProfiles[0]->id,
                'relation_type' => 'like',
            ], ['project_id' => $projectId]);
        }
    }
}
